# Server Port
server:
  port: 8181

# JWT secret key
jwt:
  secret-key: "SECRET"

# DB Information
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usersdb
    username: root
    password: Choclaholic101
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
