server:
  port: 9001

# JWT secret key
jwt:
  secret-key: "ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength"
password:
  encoder:
    secret: "secret"
    iteration: 33
    keylength: 256

# DB Information
spring:
  data:
    mongodb:
      uri: mongodb+srv://root:Choclaholic101@revaturebookshelfdb.01dfm.mongodb.net/bookshelfdb?retryWrites=true&w=majority

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/usersdb
#    username: root
#    password: rootpass
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update

# Swagger-UI
springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: com.reavture.bookshelf.loginservice
  pathsToMatch: /**